### PR TITLE
Mention text editors for writing programs

### PR DESCRIPTION
**Pull request by mkcor**
It is not obvious at all for beginners who have never used a text editor...

This change follows feedback and interactions I had with students here at PyCon 2015 (Django Carrots workshop).

We can recommend Notepad++ to Windows users, nano to Linux users, etc.

### CODE REVIEW

**Comment by sguermond** [comment]
Good point, my group had to install something as well. Sublime Text is a great free text editor that works on all platforms.

**Comment by mstepniowski** [comment]
Looks good, thanks for doing this! I would probably recommend Sublime Text for everyone instead of pointing them to Wikipedia though.

**Comment by mkcor** [comment]
@sguermond No, it is absolutely not free (see http://www.sublimetext.com/buy) so I don't believe its use should be promoted in a community context.

**Comment by LukeSwart** [comment]
Nano (Linux) and Notepad++ (Windows) are working well for my group. They're simple and I think they're a good place to start.

**Comment by sguermond** [comment]
It can be used for free, legally. Their website asks you to buy if you want, but it can be downloaded and used without registration for as long as you want.

**Comment by suff** [comment]
I've asked my group in the first email about the text editor they want to use and because one was already using Sublime Text and the other did not use anything I sugested to use the same editor. IMO Sublime Text is a good choice

**Comment by mstepniowski** [comment]
Irregardless of the final decision, linking to a list of editors to use is still better than not mentioning editor at all. I'm going to merge this change in. Thanks, @mkcor.

**Pull request merged**
